import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Men of Law Corporate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>

      <main>
        <hero className="d-block position-relative vh-100 h-100 mh-100 w-100 mt-5">
          {/* <Image
          style={{ zIndex: 1 }}
          src="https://previews.123rf.com/images/ijeab/ijeab1805/ijeab180500064/102335348-law-advice-and-legal-services-concept-lawyer-and-attorney-having-team-meeting-at-law-firm-.jpg"
          layout="fill"
        ></Image> */}

          <div className="container-fluid position-absolute top-50 start-50 translate-middle w-100 overlay-dark p-5">
            <div className="container">
              <h1 className="heading-1 text-gold">We're here for you</h1>
              <p className="sub-heading-1 text-light">
                Online legal service that provides legal information and advice.
              </p>
              <button className="btn hero-btn dark-bg text-light" type="button">
                Get Started
              </button>
            </div>
          </div>
        </hero>
      </main>
    </div>
  );
}
